[package]
name = "exporter"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>"]
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
futures = "0.3"
ruffle_core = { path = "../core", features = ["deterministic"] }
ruffle_render_wgpu = { path = "../render/wgpu", features = ["clap"] }
image = "0.24.5"
log = "0.4"
walkdir = "2.3.2"
indicatif = "0.17"
anyhow = "1.0"
rayon = "1.6.1"

[features]
avm_debug = ["ruffle_core/avm_debug"]
render_debug_labels = ["ruffle_render_wgpu/render_debug_labels"]
render_trace = ["ruffle_render_wgpu/render_trace"]
lzma = ["ruffle_core/lzma"]
